package it.dmsoft.flowmanager.agent.api.flows.mapper;

import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.ReportingPolicy;

import it.dmsoft.flowmanager.agent.api.flows.model.ExecutionFlowData;
import it.dmsoft.flowmanager.common.model.FullFlowData;

@Mapper(componentModel = "spring", unmappedTargetPolicy = ReportingPolicy.WARN)
public interface FlowDataMapper {
    
    @Mapping(target = "description", source = "fullFlowData.person.description")
	@Mapping(target = "flowId", source = "fullFlowData.flow.id")
	@Mapping(target = "flowDesc", source = "fullFlowData.flow.description")
	@Mapping(target = "flowGruppo", source = "fullFlowData.group.id")
	@Mapping(target = "flowCodInterfaccia", source = "fullFlowData.interface.id")
	@Mapping(target = "flowStato", source = "fullFlowData.flow.enabled")
	@Mapping(target = "flowTipFlusso", source = "fullFlowData.model.type")
	@Mapping(target = "flowDirezione", source = "fullFlowData.model.direction")
	@Mapping(target = "flowLibreria", source = "fullFlowData.model.database")
	@Mapping(target = "flowFile", source = "fullFlowData.flow.file")
	@Mapping(target = "flowMembro", source = "")
	@Mapping(target = "flowLibSource", source = "")
	@Mapping(target = "flowFileSource", source = "")
	@Mapping(target = "flowMembroSource", source = "")
	@Mapping(target = "flowFolder", source = "fullFlowData.flow.folder")
	@Mapping(target = "flowFileName", source = "fullFlowData.flow.file")
	@Mapping(target = "flowFormato", source = "fullFlowData.model.fileFormat")
	@Mapping(target = "flowDelimRecord", source = "fullFlowData.model.recordDelimiter")
	@Mapping(target = "flowDelimStringa", source = "fullFlowData.model.stringDelimiter")
	@Mapping(target = "flowRimozSpazi", source = "fullFlowData.model.removingSpaces")
	@Mapping(target = "flowDelimCampo", source = "fullFlowData.model.fieldDelimiter")
	@Mapping(target = "flowRiempCampo", source = "fullFlowData.model.numericFilling")
	@Mapping(target = "flowCodepage", source = "fullFlowData.model.destCharset")
	@Mapping(target = "flowModAcquisizione", source = "")
	@Mapping(target = "flowFromCcsid", source = "fullFlowData.model.sourceCharset")
	@Mapping(target = "flowPgmControllo", source = "")
	@Mapping(target = "flowTipologiaConn", source = "fullFlowData.interface.connectionType")
	@Mapping(target = "flowHost", source = "fullFlowData.interface.host")
	@Mapping(target = "flowPort", source = "fullFlowData.interface.port")
	@Mapping(target = "flowRemoteFolder", source = "fullFlowData.flow.remoteFolder")
	@Mapping(target = "flowRemoteFileName", source = "fullFlowData.flow.remoteFile")
	@Mapping(target = "flowUtente", source = "fullFlowData.interface.user")
	@Mapping(target = "flowPassword", source = "fullFlowData.interface.password")
	@Mapping(target = "flowUtenteSftp", source = "fullFlowData.interface.sftpAlias")
	@Mapping(target = "flowIntegrityCheck", source = "fullFlowData.model.integrityCheck")
	@Mapping(target = "flowFlNameSemaforo", source = "fullFlowData.flow.integrityFileName")
	@Mapping(target = "flowNumTentaRicez", source = "fullFlowData.model.retry")
	@Mapping(target = "flowIntervalloRetry", source = "fullFlowData.model.retryInterval")
	@Mapping(target = "flowRetention", source = "fullFlowData.model.retention")
	@Mapping(target = "flowCompression", source = "fullFlowData.model.compression")
	@Mapping(target = "flowDeCompression", source = "fullFlowData.model.decompression")
	@Mapping(target = "flowBackup", source = "")
	@Mapping(target = "flowInviaMail", source = "fullFlowData.model.sendMail")
	@Mapping(target = "flowLetteraOk", source = "fullFlowData.flow.notificationOk")
	@Mapping(target = "flowLetteraKo", source = "fullFlowData.flow.notificationKo")
	@Mapping(target = "flowProgPerson", source = "")
	@Mapping(target = "flowKnownHtFl", source = "fullFlowData.interface.knownHost")
	@Mapping(target = "flowKeyFl", source = "fullFlowData.interface.keyFile")
	@Mapping(target = "flowModalitaPassiva", source = "fullFlowData.interface.passiveMode")
	@Mapping(target = "flowJobDesc", source = "")
	@Mapping(target = "flowLibJobDesc", source = "")
	@Mapping(target = "flowCancellaFil", source = "fullFlowData.model.deleteFile")
	@Mapping(target = "flowRisottomet", source = "")
	@Mapping(target = "flowLunghezzaFlFlat", source = "fullFlowData.flow.lengthFixed")
	@Mapping(target = "flowTipoTrasferimento", source = "fullFlowData.model.type")
	@Mapping(target = "flowBypassQtemp", source = "")
	@Mapping(target = "flowEsistenzaFile", source = "")
	@Mapping(target = "flowLetteraFlusso", source = "")
	@Mapping(target = "flowAggNomiCol", source = "")
	@Mapping(target = "flowCreaVuoto", source = "")
	@Mapping(target = "flowInternaz", source = "")
	@Mapping(target = "flowSostValNull", source = "")
	@Mapping(target = "flowElimNomCol", source = "")
	@Mapping(target = "flowFlagOkVuoto", source = "")
	@Mapping(target = "flowFtpSecure", source = "fullFlowData.interface.secureFtp")
	@Mapping(target = "flowInteractiveType", source = "")
	@Mapping(target = "flowInteractiveProgram", source = "")
	@Mapping(target = "flowInteractiveResult", source = "")
	@Mapping(target = "flowInteractiveCommand", source = "")
	@Mapping(target = "flowDelaySemaforo", source = "")
	@Mapping(target = "flowHashUnico", source = "fullFlowData.model.uniqueHash")
	@Mapping(target = "flowExportFlag", source = "")
	@Mapping(target = "flowExportCode", source = "")
	@Mapping(target = "flowFetchSize", source = "")
	@Mapping(target = "flowCharEmptySpace", source = "")
	ExecutionFlowData convert(FullFlowData fullFlowData);

}
