name: Build Maven Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Store JAR as artifact
        uses: actions/upload-artifact@v3
        with:
          name: DMFlowManager-app-jar
          path: DMFlowManager-app/target/*.jar
